### ISSUE TITLE
Data debugging checklist

### ISSUE THREAD

**Issue by hampelm** [hampelm/ideas#21]
- [ ] Do the counts match? 
- [ ] Is there data missing? Why? 
- [ ] Capitalization and spelling good
- [ ] Google iiiittttt
